sudo: true
dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

install:
  - composer install --no-interaction --no-progress --no-suggest

script:
  - ./vendor/bin/phpunit tests/

notifications:
  email:
    - rozdol@gmail.com